# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uwLsnPZvqP0QMCFhnEEqaRi4eiscymP
"""

for i in range (1,20):
    print(i+2)

#print only those number which is divided by 7 and 3 using range(10,50)
for i in range(10,50):
  if i%21==0:
    print(i)

for i in range(1,10):
  print(i*7)

for i in range(10,50):
  if i%3==0 and i%7==0:
    print(i)

for i in range (5,0,-1):
  print(i)

#calculate the square of all the number which is divded by 9 using range (4,80)
for i in range(1,10):
    print(i*"**")

#print those  no .where 1st digit is 5 using range(1,100)
for i in range (1,100):
  if i%10==5 and i>5:
    print(i)

#calculate the sq of even no and cube of odd using range(20,35)
for i in range (20,35):
  if i%2==0:
    print(i**2,"square of even no",i)
    print(=============)
  else:
    print(i**3,"cube of no",i)

#creat a table 2
for i in range(1,11):
  print(2,"*",i,"=",i*2)

#creat 2 blank list and even element in even list and odd element in odd list
list1=[]
list2=[]
for i in range(55,102):
  if i%2==0:
    list1.append(i)
  else:
    if i%3==0:
      list2.append(i)

print(list1)

print(list2)

#count the even numbers in the range of 120,189
count=0
for i in range (120,189):
  if i%2==0:
    count+=1
print(count)

#count the name of those people whose name length is more than 5
name=["aman","pankaj","alok","vishal","abhiyanshu","priyanshu"]
count = 0
for i in name:
  if len(i)>5:
    count+=1
print(count)

def add(x,y):
  return x+y

add(2,4)

#cal cube
def cube(x):
  return x**(1/3)

cube(27)

def squ(y):
  return y**2

def sqr(y):
  return y**(1/2)

def area(r):
  """ this function is use for calculating """
  return 3.14*(r**2)

?area

def tra(b,h):
  """breadth ,hight"""
  return (1/2)*b*h

?tra



def solid ():
  name=input("enter the name of formula")
  if name.lower()=="tsa":
    r= float(input("enter the r for TSA"))
    h=float(input("enter the h for TSA"))
    return 2*3.14*r*(r+h)
  elif name.lower()=="csa":
    r= float(input("enter the r for CSA"))
    h=float(input("enter the h for CSA"))
    return 2*3.14*r*h
  else:
    print("wrong name")